/* SPDX-License-Identifier: GPL-2.0+ */

#include <asm/arch/plat-sun300iw1p1/clock_autogen_aon.h>


#define CCMU_FUNC_CFG_REG   (SUNXI_CCM_AON_BASE + PLL_FUNC_CFG_REG)
#define CCMU_PLL_T_HEAD__CTRL_REG (SUNXI_CCM_AON_BASE + T_HEAD_CLK_REG)
#define CCMU_ANSC_CLK_REG   (SUNXI_CCM_AON_BASE + ANSC_CLK_REG)
#define CCMU_PLL_VIDEO_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_VIDEO_CTRL_REG)
#define CCMU_PLL_CPUX_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_CPU_CTRL_REG)
#define CCMU_PLL_PERI_CTRL0_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_CTRL0_REG)
#define CCMU_PLL_PERI_CTRL1_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_CTRL1_REG)
#define CCMU_AHB_CLK_REG	     (SUNXI_CCM_AON_BASE + AHB_CLK_REG)
#define CCMU_APB_CLK_REG	     (SUNXI_CCM_AON_BASE + APB_CLK_REG)
#define CCMU_APB_SPEC_CLK_REG	 (SUNXI_CCM_AON_BASE + APB_SPEC_CLK_REG)
