
/* SPDX-License-Identifier: GPL-2.0+ */

#include <asm/arch/plat-sun300iw1p1/cpu_autogen.h>

#define SUNXI_CCM_ON_BASE	SUNXI_CCU_AON_BASE
#define SUNXI_CCM_APP_BASE	SUNXI_CCU_APP_BASE
#define SUNXI_CCM_BASE		SUNXI_CCU_APP_BASE

#define SUNXI_SS_BASE		SUNXI_CE_BASE

#define SUNXI_PIO_BASE		SUNXI_GPIO_BASE
#define SUNXI_R_PIO_BASE	(0x42000540)
#define SUNXI_CCM_AON_BASE	SUNXI_CCU_AON_BASE

#define SUNXI_WDT_BASE		SUNXI_RTC_WDG_BASE

#define SUNXI_MMC0_BASE		SUNXI_SMHC0_BASE
#define SUNXI_MMC1_BASE		SUNXI_SMHC1_BASE

/*USB DRD AS ehci0*/
#define SUNXI_USBOTG_BASE	SUNXI_USB0_BASE
#define SUNXI_EHCI0_BASE	0x44101000

#define SUNXI_RTC_BASE		SUNXI_PRCM_BASE
#define SUNXI_RTC_DATA_BASE	(SUNXI_PRCM_BASE + 0x200)

#define SUNXI_DMA_BASE		 SUNXI_DMAC0__SGDMA__BASE

#define PLAT_TCIP_BASE_ADDR	(SUNXI_RISCV_CLINT_BASE)
#define PLAT_CLIC_BASE_ADDR	(PLAT_TCIP_BASE_ADDR + 0x800000)

#define SUNXI_SPIF_BASE		SUNXI_SPI_FLASH_BASE

#define H_MTIME_REG                   (SUNXI_PLMT_BASE + 0x4)
#define L_MTIME_REG                   (SUNXI_PLMT_BASE)

#define PIOC_REG_o_POW_MS_VAL 0x34c

#define PIOC_REG_POW_VAL (SUNXI_PIO_BASE + PIOC_REG_o_POW_MS_VAL)

#define PIOC_VAL_Px_3_3V_VOL 0
#define PIOC_VAL_Px_1_8V_VOL 1

#ifndef __ASSEMBLY__
int sunxi_get_sid(unsigned int *sid);
#endif
