# Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
#
# Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
# the people's Republic of China and other countries.
# All Allwinner Technology Co.,Ltd. trademarks are used with permission.
#
# DISCLAIMER
# THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
# IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
# IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
# ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
# ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
# COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
# YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
#
# THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
# PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
# WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
# THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
# OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
# IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
#config file for sun300iw1
#
BOARD_BUILD_NBOOT=spinorpmc spinorpmcver spinorfastboot spinorfastbootpmc mmcpmc mmcpmcver mmcfastboot mmcfastbootpmc mmcfastbootaiglass spinorfastbootaiglass nandfastboot nandfastbootpmc nandpmc
SUPPORT_BOARD=v821
ARCH=riscv
CPU=ads_rv32
PLATFORM = sun300iw1p1
CFG_AW_CHIPS=y
CFG_SUNXI_GPIO_V2=y
CFG_USE_DCACHE=y

CFG_BOOT0_RUN_ADDR=0x2000000
CFG_SYS_INIT_RAM_SIZE=0x21c00
CFG_FES1_RUN_ADDR=0x2008000
CFG_SBOOT_RUN_ADDR=0x2000480
CFG_SUNXI_MEMOP=y
CFG_ARCH_RISCV=y
CFG_RISCV_E907=y
CFG_DEFAULT_BOOT_RTOS=y

CFG_SUNXI_WATCHDOG=y
CFG_SUNXI_EFUSE =y
CFG_SUNXI_EFUSE_SW_EBP=y
CFG_SUNXI_EFUSE_SW_ECC_HAMMING=y

# sboot static lib
CFG_SUNXI_SBOOT_LD_LIB=y
# CFG_SUNXI_SBOOT_LIB=y

CFG_PMBOOT_RUN_ADDR=0x80f80000
CFG_PMBOOT_SIZE=0x20000

# dynamic opensbi fw
CFG_OPENSBI_FW_DYNAMIC=y

#secure
CFG_AW_CERT=y
CFG_X509_CERT_DISABLE=y

CFG_BOOT0_WIRTE_RTC_TO_FLASH=y
CFG_FLASHFLAG_RTC_INDEX=0x0
CFG_FLASHFLAG_RTC_BIT=0x2
CFG_FLASHFLAG_RTC_RV_PARTITION_BIT=0x6

#cpu boot clk
#CFG_SUNXI_VF_2_1=y

CFG_SUNXI_PHY_KEY=y
CFG_GPADC_KEY=y

# CFG_UART_BAUD_1500000=y

# chips
CFG_V821B_CHIP=y
# CFG_CHIP_V821=y



