# Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
#
# Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
# the people's Republic of China and other countries.
# All Allwinner Technology Co.,Ltd. trademarks are used with permission.
#
# DISCLAIMER
# THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
# IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
# IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
# ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
# ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
# COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
# YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
#
# THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
# PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
# WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
# THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
# OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
# IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
# OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
#config file for sun300iw1
#
FILE_EXIST=$(shell if [ -f $(TOPDIR)/board/$(PLATFORM)/common.mk ]; then echo yes; else echo no; fi;)
EXT_FILE_EXIST=$(shell if [ -f $(TOPDIR)/board/$(PLATFORM)/common$(LICHEE_BOARD).mk ]; then echo yes; else echo no; fi;)
ifeq (x$(EXT_FILE_EXIST),xyes)
include $(TOPDIR)/board/$(PLATFORM)/common$(LICHEE_BOARD).mk
else ifeq (x$(FILE_EXIST),xyes)
include $(TOPDIR)/board/$(PLATFORM)/common.mk
else
include $(TOPDIR)/board/$(CP_BOARD)/common.mk
endif

MODULE=mmcfastbootaiglass
CFG_SUNXI_SDMMC=y
CFG_SUNXI_ELF =y
CFG_SUNXI_FDT =y
CFG_SUNXI_GPT =y
CFG_SUNXI_ENV =y
CFG_SUNXI_ENV_SIZE =0x1000
CFG_SUNXI_HAVE_REDUNDENV=y
#CFG_SUNXI_NO_UPDATE_FDT_CHOSEN=y
CFG_MMC_GPT_ARD=0

CFG_BOOT0_LOAD_KERNEL=y
CFG_KERNEL_BOOTIMAGE=y
CFG_LOAD_DTB_FROM_KERNEL=y
CFG_KERNEL_CHECKSUM=n #y will check kernel checksum in bimage, but slower
CFG_MMC_KERNEL_OFFSET=0x400 # partition mbr size 512 * 1024 / 512 = 0x400 sector
CFG_MMC_LOGICAL_OFFSET=40960
CFG_KERNEL_LOAD_ADDR=0x82000000
CFG_SUNXI_FDT_ADDR=0x80800000
CFG_FASTBOOT_EFEX=y
CFG_RESERVE_FDT_SIZE=0x30000
#CFG_SUNXI_SUPPORT_RAMDISK=y # 支持ramdisk镜像，主要用于recovery系统
CFG_RAMDISK_ADDR=0x80700000 # ramdisk镜像存放地址
CFG_BOOT0_LOAD_FLASH=y
CFG_BOOT0_LOAD_ISPPARM=y
CFG_ISPPARAM_LOAD_ADDR=0x83929000
CFG_ISPPARAM_SIZE=0x10 #unit:sector
CFG_ISPPARAM_PARTITION=y
CFG_EARLY_BOOT_RISCV=y

# ISP Param
CFG_BOOT0_WIRTE_RTC_TO_ISP=y
CFG_ISPFLAG_RTC_INDEX=0x0
CFG_ISPFLAG_RTC_VALUE=0x1

#compression
CFG_SUNXI_LZMA=y
#CFG_SUNXI_GUNZIP=y
CFG_SUNXI_LZ4=y

CFG_SHORT_COMMIT_LOG=y

## enable simpleboot
#CFG_SUNXI_SIMPLEBOOT=y
#CFG_BOOT0_RUN_ADDR=0x83000000
#CFG_BOOT0_SIZE_LIMIT=0x10000
#CFG_BOOTTIME_RTC_IDX=4

#CFG_RECORD_BOOTTIME=y
CFG_RECORD_BOOTTIME_MAX=36
CFG_BOOTTIME_BASE=0x43032004
CFG_BOOTTIME_PREP_BIT=0x1
CFG_BOOTTIME_PREP_REG=0x43032000

CFG_ENABLE_LDO28=y
CFG_PARALLEL_DECOMP_KERNEL=y

# CFG_SUNXI_PL_1V8=y
# CFG_PMC_EN1_FOR_PWRCTRL=y
# CFG_PMC_EN2_FOR_PWRCTRL=y
CFG_PMC_PL6_FOR_PWRCTRL=y
