/*
 * Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the people's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef  __private_uboot_h__
#define  __private_uboot_h__

#include "spare_head.h"

#ifndef CONFIG_SUNXI_DEBUG_BUF
#define CONFIG_SUNXI_DEBUG_BUF
#ifndef CONFIG_SUNXI_DEBUG_BUF_SIZE
#define CONFIG_SUNXI_DEBUG_BUF_SIZE   (1 * 1024 * 1024)
#endif
#endif

#define UBOOTA	0
#define UBOOTB	1

/******************************************************************************/
/*               the control information stored in file head                  */
/******************************************************************************/
struct spare_boot_ctrl_head
{
	unsigned int  jump_instruction;   /* one intruction jumping to real code */
	unsigned char magic[MAGIC_SIZE];  /* ="u-boot" */
	unsigned int  check_sum;          /* generated by PC */
	unsigned int  align_size;		  /* align size in byte */
	unsigned int  length;             /* the size of all file */
	unsigned int  uboot_length;       /* the size of uboot */
	unsigned char version[8];         /* uboot version */
	unsigned char platform[8];        /* platform information */
	int           reserved;        /*stamp space, 16bytes align */
};

/******************************************************************************/
/*                          the data stored in file head                      */
/******************************************************************************/
struct spare_boot_data_head
{
	unsigned int                dram_para[32];
	int                         run_clock;              /* Mhz */
	int                         run_core_vol;           /* mV */
	int                         uart_port;              /* UART ctrl num */
	normal_gpio_cfg             uart_gpio[2];           /* UART GPIO info */
	int                         twi_port;               /* TWI ctrl num */
	normal_gpio_cfg             twi_gpio[2];            /* TWI GPIO info */
	int                         work_mode;              /* boot,usb-burn, card-burn */
	int                         storage_type;           /* 0:nand 1:sdcard 2:spinor */
	normal_gpio_cfg             nand_gpio[32];          /* nand GPIO info */
	char                        nand_spare_data[256];	/* nand info */
	normal_gpio_cfg             sdcard_gpio[32];		/* sdcard GPIO info */
	char                        sdcard_spare_data[256];	/* sdcard info */
	unsigned char               secureos_exist;
	unsigned char               monitor_exist;
	unsigned char               func_mask;              /* see enum UBOOT_FUNC_MASK_EN */
	uint8_t			    uboot_backup;		/* use in OTA update */
	unsigned int                uboot_start_sector_in_mmc;  /*use in OTA update */
	int                         dtb_offset;                 /*device tree in uboot */
	int                         boot_package_size;          /*boot package size, boot0 pass this value */
	unsigned int                dram_scan_size;             /*dram real size */
	int                         reserved[1];                /*reseved,256bytes align */
	/*expend boot_ext[0](int[4]) in uboot 2014*/
	uint16_t                    pmu_type;
	uint16_t                    uart_input;
	uint16_t                    key_input;
	uint8_t                     secure_mode; /*update by update_uboot*/
	uint8_t                     debug_mode;  /*update by update_uboot*/
	int                         reserved2[2];
};

struct spare_boot_ext_head
{
	int data[4];
};

typedef struct spare_boot_head_t
{
	struct spare_boot_ctrl_head    boot_head;
	struct spare_boot_data_head    boot_data;
	struct spare_boot_ext_head     boot_ext[15];
	char   hash[64];
}uboot_head_t;

struct spare_monitor_head
{
	unsigned int  jump_instruction;   /* one intruction jumping to real code */
	unsigned char magic[MAGIC_SIZE];  /* ="u-boot" */
	unsigned int  scp_base;           /* generated by PC */
	unsigned int  nboot_base;         /* align size in byte */
	unsigned int  nos_base;           /* the size of all file */
	unsigned int  secureos_base;      /* the size of uboot */
	unsigned char version[8];         /* uboot version */
	unsigned char platform[8];        /* platform information */
	int           reserved[1];         /*stamp space, 16bytes align */
};

struct display_params {
	char resolution[32];
	char margin[32];
	char vendorid[64];

	int format;      /* RGB / YUV444 / YUV422 / YUV420     */
	int depth;       /* Color depth: 8 / 10 / 12 / 16      */
	int eotf;	/* Electro-Optical Transfer Functions */
	int color_space; /* BT.601 / BT.709 / BT.2020          */

	/*
	 * make sure sizeof(struct display_params) == 256
	 * reserved size = 256 -128 - 4*4 = 112
	 */
	char reserved[112];
};

/*size is 128*/
typedef struct spare_parameter_ctrl_head_t {
	unsigned int crc;
	unsigned char magic[MAGIC_SIZE];
	unsigned int length;
	char reserved[112];
} __attribute__((packed)) spare_parameter_ctrl_head;

/*size is 4096-128*/
typedef struct spare_parameter_data_head_t {
	struct display_params display_param;
	char reserved[3712];
} __attribute__((packed)) spare_parameter_data_head;

/*size is 4096*/
typedef struct spare_parameter_head_t {
	spare_parameter_ctrl_head para_head;
	spare_parameter_data_head para_data;
} __attribute__((packed)) spare_parameter_head;

extern struct spare_boot_head_t uboot_spare_head;
extern unsigned long get_spare_head_size(void);

enum UBOOT_FUNC_MASK_EN {
	UBOOT_FUNC_MASK_BIT_BOOTLOGO = (1 << 0),
	UBOOT_FUNC_MASK_BIT_FORCE_ROTPK = (1 << 1),
	UBOOT_FUNC_MASK_BIT_BURN_ROTPK = (1 << 2),
	UBOOT_FUNC_MASK_ALL	  = (0xFF)
};
#endif
