/*
 * Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the people's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * Copyright (C) 2016 Allwinner.
 * weidonghui <weidonghui@allwinnertech.com>
 *
 * SUNXI AXP1530  Driver
 *
 */

#ifndef __AXP1530_H__
#define __AXP1530_H__

#include <arch/axp.h>

//PMIC chip id reg03:bit7-6  bit3-
#define   AXP1530_CHIP_ID              (0x48)
#define   AXP313A_CHIP_ID              (0x4B)
#define   AXP313B_CHIP_ID              (0x4C)
#define   AXP323_CHIP_ID              (0x49)


#ifdef CFG_SUNXI_TWI
#define AXP1530_DEVICE_ADDR			400000
#define AXP1530_RUNTIME_ADDR			(0x36)
#else
#define AXP1530_DEVICE_ADDR			(0x3A3)
#define AXP1530_RUNTIME_ADDR			(0x2d)
#endif


/* define AXP1530 REGISTER */
#define	AXP1530_POWER_ON_SOURCE_INDIVATION			(0x00)
#define	AXP1530_POWER_OFF_SOURCE_INDIVATION			(0x01)
#define	AXP1530_VERSION								(0x03)
#define	AXP1530_OUTPUT_POWER_ON_OFF_CTL				(0x10)
#define AXP1530_DCDC_DVM_PWM_CTL					(0x12)
#define	AXP1530_DC1OUT_VOL							(0x13)
#define	AXP1530_DC2OUT_VOL          				(0x14)
#define	AXP1530_DC3OUT_VOL          				(0x15)
#define	AXP1530_ALDO1OUT_VOL						(0x16)
#define	AXP1530_DLDO1OUT_VOL						(0x17)
#define	AXP1530_POWER_DOMN_SEQUENCE					(0x1A)
#define	AXP1530_PWROK_VOFF_SERT						(0x1B)
#define AXP1530_POWER_WAKEUP_CTL					(0x1C)
#define AXP1530_OUTPUT_MONITOR_CONTROL				(0x1D)
#define	AXP1530_POK_SET								(0x1E)
#define	AXP1530_IRQ_ENABLE							(0x20)
#define	AXP1530_IRQ_STATUS							(0x21)
#define AXP1530_WRITE_LOCK							(0x70)
#define AXP1530_ERROR_MANAGEMENT					(0x71)
#define	AXP1530_DCDC1_2_POWER_ON_DEFAULT_SET		(0x80)
#define	AXP1530_DCDC3_ALDO1_POWER_ON_DEFAULT_SET	(0x81)

int axp1530_probe_power_key(void);
int axp1530_set_ddr_voltage(int set_vol);
int axp1530_set_pll_voltage(int set_vol);
int axp1530_set_efuse_voltage(int set_vol);
int axp1530_set_sys_voltage(int set_vol, int onoff);
int axp1530_reg_read(u8 addr, u8 *val);
int axp1530_reg_write(u8 addr, u8 val);
int axp1530_axp_init(u8 power_mode);
int axp1530_set_cpu_voltage_ext(int set_vol);
#endif /* __AXP1530_REGS_H__ */


