/*
 * Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the people's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * (C) Copyright 2015 Hans de Goede <hdegoede@redhat.com>
 */

#ifndef _SUNXI_CPU_H
#define _SUNXI_CPU_H

#include <config.h>

#if defined(CONFIG_SUNXI_NCAT)
#include <arch/cpu_ncat.h>
#elif defined(CONFIG_SUNXI_NCAT_2_0)
#include <arch/cpu_ncat_2_0.h>
#elif defined(CONFIG_SUNXI_NCAT_V2)
#include <arch/cpu_ncat_v2.h>
#elif defined(CONFIG_SUNXI_VERSION1)
#include <arch/cpu_version1.h>
#elif defined(CONFIG_ARCH_SUN60IW1)
#include <arch/sun60iw1p1/cpu_sun60iw1.h>
#elif defined(CONFIG_ARCH_SUN60IW2)
#include <arch/sun60iw2p1/cpu_sun60iw2.h>
#elif defined(CONFIG_ARCH_SUN55IW3)
#include <arch/sun55iw3p1/cpu_sun55iw3.h>
#elif defined(CONFIG_ARCH_SUN55IW5)
#include <arch/sun55iw5p1/cpu_sun55iw5.h>
#elif defined(CONFIG_ARCH_SUN55IW6)
#include <arch/sun55iw6p1/cpu_sun55iw6.h>
#elif defined(CONFIG_ARCH_SUN300IW1)
#include <arch/sun300iw1p1/cpu_sun300iw1.h>
#elif defined(CONFIG_ARCH_SUN65IW1)
#include <arch/sun65iw1p1/cpu_sun65iw1.h>
#elif defined(CONFIG_ARCH_SUN251IW1)
#include <arch/sun251iw1p1/cpu_sun251iw1.h>
#elif defined(CONFIG_ARCH_SUN50IW15)
#include <arch/sun50iw15p1/cpu_sun50iw15.h>
#elif defined(CONFIG_ARCH_SUN252IW1)
#include <arch/sun252iw1p1/cpu_sun252iw1.h>
#else
#error "Unsupported plat"
#endif

#endif /* _SUNXI_CPU_H */
