/*
 * Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the people's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * for clk
 */

#ifndef __CCMU_AON_H
#define __CCMU_AON_H

#include <config.h>
#include <arch/cpu.h>
#include <arch/sun300iw1p1/clock_autogen_aon.h>
#include <arch/sun300iw1p1/cpu_autogen.h>

#define SUNXI_CCM_AON_BASE SUNXI_CCU_AON_BASE
/* pll list */

#define CCMU_PLL_PERI0_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_CTRL0_REG)
#define CCMU_PLL_PERI1_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_CTRL1_REG)
#define CCMU_PLL_DDR0_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_DDR_CTRL_REG)
#define CCMU_PLL_PERI_PAT0_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_PAT0_CTRL_REG)
#define CCMU_PLL_PERI_PAT1_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_PAT1_CTRL_REG)
#define CCMU_PLL_DDR_PAT0_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_DDR_PAT0_CTRL_REG)
#define CCMU_PLL_DDR_PAT1_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_DDR_PAT1_CTRL_REG)
#define CCMU_PLL_CPU_BIAS_REG	 (SUNXI_CCM_AON_BASE + PLL_CPU_BIAS_REG)
#define CCMU_PLL_PERI_BIAS_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_BIAS_REG)
#define CCMU_PLL_DDR_BIAS_REG	 (SUNXI_CCM_AON_BASE + PLL_DDR_BIAS_REG)
#define CCMU_PLL_CPU_TUN_REG		 (SUNXI_CCM_AON_BASE + PLL_CPU_TUN_REG)
#define CCMU_PLL_FUNC_CFG_REG	 (SUNXI_CCM_AON_BASE + PLL_FUNC_CFG_REG)

#define CCMU_PLL_CPUX_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_CPU_CTRL_REG)
#define CCMU_AON_PLL_CPU_D_1      (0)
#define CCMU_AON_PLL_CPU_D_2      (1)
#define CCMU_AON_PLL_CPU_D_4      (3)
#define CCMU_AON_PLL_CPU_M_1      (0)
#define CCMU_AON_PLL_CPU_M_2      (1)
#define CCMU_AON_PLL_CPU_M_3      (2)
#define CCMU_AON_PLL_CPU_M_4      (3)
#define CCMU_AON_PLL_CPU_M_5      (4)
#define CCMU_AON_PLL_CPU_N_24     (23)
#define CCMU_AON_PLL_CPU_N_25     (24)
#define CCMU_AON_PLL_CPU_N_27     (26)
#define CCMU_AON_PLL_CPU_N_30     (29)
#define CCMU_AON_PLL_CPU_N_40     (39)
#define CCMU_AON_PLL_CPU_N_41     (40)
#define CCMU_AON_PLL_CPU_N_45     (44)
#define CCMU_AON_PLL_CPU_N_48     (47)
#define CCMU_AON_PLL_CPU_N_50     (49)
#define CCMU_AON_PLL_CPU_N_54     (53)
#define CCMU_AON_PLL_CPU_N_56     (55)
#define CCMU_AON_PLL_CPU_N_60     (59)
#define CCMU_AON_PLL_CPU_N_67     (66)
#define CCMU_AON_PLL_CPU_N_96     (95)
#define CCMU_AON_PLL_CPU_N_99     (98)
#define CCMU_AON_PLL_CPU_N_118    (117)
#define CCMU_AON_PLL_CPU_N_192    (191)

#define CCMU_PLL_PERI_CTRL0_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_CTRL0_REG)
#define CCMU_PLL_PERI_CTRL1_REG	 (SUNXI_CCM_AON_BASE + PLL_PERI_CTRL1_REG)
#define CCMU_PLL_VIDEO_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_VIDEO_CTRL_REG)
#define CCMU_PLL_CSI_CTRL_REG	 (SUNXI_CCM_AON_BASE + PLL_CSI_CTRL_REG)
#define CCMU_PLL_CSI_PAT0_REG	 (SUNXI_CCM_AON_BASE + PLL_CSI_PAT0_CTRL_REG)
#define CCMU_PLL_CSI_PAT1_REG	 (SUNXI_CCM_AON_BASE + PLL_CSI_PAT1_CTRL_REG)

#define CCMU_AHB_CLK_REG	     (SUNXI_CCM_AON_BASE + AHB_CLK_REG)
#define CCMU_APB_CLK_REG	     (SUNXI_CCM_AON_BASE + APB_CLK_REG)
#define CCMU_APB_SPEC_CLK_REG	 (SUNXI_CCM_AON_BASE + APB_SPEC_CLK_REG)

#define CCMU_E90X_CLK_REG	     (SUNXI_CCM_AON_BASE + E907_CLK_REG)
#define CCMU_E90X_CLK_CPU_M_1    (0)
#define CCMU_E90X_CLK_CPU_M_2    (1)

#define CCMU_A27_CLK_REG	     (SUNXI_CCM_AON_BASE + A27L2_CLK_REG)
#define CCMU_A27_CLK_CPU_M_1     (0)
#define CCMU_A27_CLK_CPU_M_2     (1)
#define CCMU_A27_CLK_CPU_M_3     (2)

#define CCMU_HOSC_FREQ_DET_REG   (SUNXI_CCM_AON_BASE + HOSC_FREQ_DET)
#define HOSC_24M_COUNTER_MIN     (35600)
#define HOSC_24M_COUNTER_MAX     (58000)
#define HOSC_40M_COUNTER_MIN     (59200)
#define HOSC_40M_COUNTER_MAX     (100000)
#define HOSC_FREQ_24M            (24)
#define HOSC_FREQ_40M            (40)

#define CCMU_FUNC_CFG_REG   (SUNXI_CCM_AON_BASE + PLL_FUNC_CFG_REG)
#endif
