/*
 * Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the people's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * (C) Copyright allwinnertech
 *
 */

#ifndef _CPU_SUN300IW1_H
#define _CPU_SUN300IW1_H
#include <arch/sun300iw1p1/cpu_autogen.h>

#define SUNXI_RTC_DATA_BASE                 (SUNXI_PRCM_BASE + 0x200)
#define SUNXI_RTC_BOOT_FLAG_ADDR            (SUNXI_PRCM_BASE + 0x1c0)
#define SUNXI_WDOG_BASE                     (SUNXI_E907_WDG_BASE)
#define SUNXI_PIO_BASE                      (SUNXI_GPIO_BASE)
#define SUNXI_R_PIO_BASE                    (0x42000540)
#define SUNXI_RTWI_BASE                     (SUNXI_TWI0_BASE)
#define SUNXI_SPIF_BASE			    (SUNXI_SPI_FLASH_BASE)
#define SUNXI_DMA_BASE              (SUNXI_DMAC0__SGDMA__BASE)

#define SUNXI_UPGRADE_FLAG_ADDR             (SUNXI_PRCM_BASE + 0x1d0)
#define SUNXI_UPGRADE_FLAG_SET              (0x429B0001)
#define SUNXI_UPGRADE_FLAG_CLEAR            (0x429B0000)

#define GPIO_BIAS_MAX_LEN (32)
#define GPIO_BIAS_MAIN_NAME "gpio_bias"
#define GPIO_POW_MODE_REG (0x0340)
#define GPIO_POW_MODE_VAL_REG		(0x0348)
#define GPIO_3_3V_MODE 0
#define GPIO_1_8V_MODE 1


#define PIOC_REG_o_POW_MOD_SEL   0x340
#define PIOC_REG_o_POW_MS_CTL   0x344
#define PIOC_REG_o_POW_MS_VAL   0x348

#define PIOC_REG_POW_MOD_SEL  (SUNXI_PIO_BASE + PIOC_REG_o_POW_MOD_SEL)
#define PIOC_REG_POW_MS_CTL   (SUNXI_PIO_BASE + PIOC_REG_o_POW_MS_CTL)
#define PIOC_REG_POW_VAL   (SUNXI_PIO_BASE + PIOC_REG_o_POW_MS_VAL)

#define PIOC_SEL_Px_3_3V_VOL 0
#define PIOC_SEL_Px_1_8V_VOL 1

#define PIOC_CTL_Px_ENABLE 0
#define PIOC_CTL_Px_DISABLE 1

#define PIOC_VAL_Px_3_3V_VOL 0
#define PIOC_VAL_Px_1_8V_VOL 1

#define PIOC_CTL_Px_DEFUALT PIOC_CTL_Px_ENABLE
#define PIOC_SEL_Px_DEFAULT PIOC_SEL_Px_1_8V_VOL

#define CCM_UART_PLATFORM_CLK     (192000000)


/* check power off*/
#define VCC33_DET_CTRL_REG		  (0x64)
#define VCCIO_THRESHOLD_MASK		  (0x7)
#define VCCIO_THRESHOLD_VOLTAGE_2_7	  (0 << 8)
#define VCCIO_THRESHOLD_VOLTAGE_2_6	  (1 << 8)
#define VCCIO_THRESHOLD_VOLTAGE_2_8	  (2 << 8)
#define VCCIO_THRESHOLD_VOLTAGE_2_9	  (3 << 8)
#define VCCIO_THRESHOLD_VOLTAGE_3_0	  (4 << 8)
#define VCCIO_THRESHOLD_VOLTAGE_3_1	  (5 << 8)
#define VCCIO_THRESHOLD_VOLTAGE_3_2	  (6 << 8)
#define VCCIO_THRESHOLD_VOLTAGE_3_3	  (7 << 8)

#define POR_RESET_CTRL_REG		  (0X24)
#define VCC33_DET_RSTN_ENABLE		  (1 << 4)

#endif /*  _CPU_SUN300IW1_H*/
