/*
 * Copyright (c) 2019-2025 Allwinner Technology Co., Ltd. ALL rights reserved.
 *
 * Allwinner is a trademark of Allwinner Technology Co.,Ltd., registered in
 * the people's Republic of China and other countries.
 * All Allwinner Technology Co.,Ltd. trademarks are used with permission.
 *
 * DISCLAIMER
 * THIRD PARTY LICENCES MAY BE REQUIRED TO IMPLEMENT THE SOLUTION/PRODUCT.
 * IF YOU NEED TO INTEGRATE THIRD PARTY’S TECHNOLOGY (SONY, DTS, DOLBY, AVS OR MPEGLA, ETC.)
 * IN ALLWINNERS’SDK OR PRODUCTS, YOU SHALL BE SOLELY RESPONSIBLE TO OBTAIN
 * ALL APPROPRIATELY REQUIRED THIRD PARTY LICENCES.
 * ALLWINNER SHALL HAVE NO WARRANTY, INDEMNITY OR OTHER OBLIGATIONS WITH RESPECT TO MATTERS
 * COVERED UNDER ANY REQUIRED THIRD PARTY LICENSE.
 * YOU ARE SOLELY RESPONSIBLE FOR YOUR USAGE OF THIRD PARTY’S TECHNOLOGY.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY ALLWINNER"AS IS" AND TO THE MAXIMUM EXTENT
 * PERMITTED BY LAW, ALLWINNER EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION REGARDING
 * THE TITLE, NON-INFRINGEMENT, ACCURACY, CONDITION, COMPLETENESS, PERFORMANCE
 * OR MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL ALLWINNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS, OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/*
 * (C) Copyright 2013-2016
 * Allwinner Technology Co., Ltd. <www.allwinnertech.com>
 *
 */

#ifndef __EFUSE_H__
#define __EFUSE_H__

#include <arch/cpu.h>

#define SID_PRCTL               (SUNXI_SID_BASE + 0x40)
#define SID_PRKEY               (SUNXI_SID_BASE + 0x50)
#define SID_RDKEY               (SUNXI_SID_BASE + 0x60)

#define SID_EFUSE               (SUNXI_SID_BASE + 0x200)
#define SID_SECURE_MODE         (SUNXI_SID_BASE + 0xA0)
#define SID_OP_LOCK  		(0xAC)

#define SID_WORK_STATUS		(3)

/*efuse power ctl*/
#define EFUSE_HV_SWITCH		(SUNXI_PMU_AON_BASE + 0x84)

#define EFUSE_FT_ZONE_LOW       (0x1c)
#define EFUSE_FT_ZONE_HIGH      (0x20)
#define RES240_TRIM_POS		(12)
#define RES_TRIM_POS		(16)
#define USB_TRIM_POS		(8)
#define RES240_TRIM_MASK	(0xf << 12)
#define RES_TRIM_MASK		(0xf << 16)
#define USB_TRIM_MASK		(0x1ff << 8)

#define EFUSE_BROM              (0x4c)
#define EFUSE_LCJS		EFUSE_BROM
#define EFUSE_ROTPK             (0x74)
#define EFUSE_NV1               (0x94)
#define EFUSE_HUK		(0x54)

/* secure enbale bit */
#define SECURE_BIT_OFFSET       (0)
#define SECURE_BIT_VAL 		(3)

/*write protect*/
#define EFUSE_WRITE_PROTECT		(0x50)

/*write protect offset*/
#define EFUSE_HUK_PROTECT_OFFSET	(24)

/* size (bit)*/
#define SID_NV1_SIZE			(32)
#define SID_ROTPK_SIZE			(256)
#define SID_HUK_SIZE			(128)

#define SUNXI_EFUSE_RAM_BASE_IN_DDR	(0x80FFFF00)
#define EFUSE_MAP_SIZE			(0x100)

/* ebp setting */
#define SID_EBP_BITMAP_START	(1664)
#define SID_EBP_BITMAP_BASE	(0xD0)
#define SID_EBP_BITMAP_WIDTH	(26)
#define SID_EBP_BITMAP_MASK	(0x3)
#define SID_EBP_MAP_BIT(i)	(SID_EBP_BITMAP_MASK << (i * 2))
#define SID_EBP_START		(1700)
#define SID_EBP_WIDTH		(12)
#define SID_EBP_POST_MASK	(0x7ff)
#define SID_EBP_CRC_SHIFT	(11)
#define SID_EBP_CRC_MASK	(0x1 << SID_EBP_CRC_SHIFT)
#define SID_EBP_IDX_MAX		(12)
#define SID_EBP_SIZE	(SID_EBP_IDX_MAX + 1)
#define SID_EBP_ID_OFFSET(i)    (SID_EBP_START + (SID_EBP_IDX_MAX * i))
#define SID_EBP_ID_MASK         (0xfff)
#define SID_EBP_ODD_BIT_SHIFT   (SID_EBP_WIDTH - 1)
#define SID_EBP_BITMAPALL_MASK	(0x3ffffff)

/* ecc setting */
#define  EFUSE_TRIM_VERSION 	0x24
#define  EFUSE_ECC_CODE 	0xE8
#define  EFUSE_VERSION_MASK	0xF
#define  ECC_NUM_MAX		4
#define  ECC_PARITY_WIDTH	8
#define  ECC_PARITY_MASK	0xFF
#define  SUNXI_ECC0_START		0
#define	 SUNXI_ECC1_START		288
#define  SUNXI_ECC2_START		352
#define  SUNXI_ECC3_START		416

#endif    /*  #ifndef __EFUSE_H__  */
