# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2007-2011
#Allwinner Technology Co., Ltd. <www.allwinnertech.com>

obj-y += cpu.o
obj-y += cache.o
obj-y += timer.o
obj-$(CONFIG_MACH_SUN300IW1) += sysmap_sun300iw1p1.o

